services:
  be:
    container_name: dryink_be
    build:
       context: .
       dockerfile: ./be/Dockerfile
    env_file: ./be/.env
    ports:
     - "${PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
 
  fe:
    container_name: dryink-fe
    build:
      context: .
      dockerfile: ./fe/Dockerfile.dev
    env_file: ./fe/.env
    ports:
      - "${PORT:-3000}:3000"
    #it mounts the local code files inside container without over writing the node_modules for hot reloading
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      #must set these envs else hot module not work, it will tell nextjs to pool for the changes
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: 100
  
  worker:
    container_name: dryink_worker
    build:
       context: .
       dockerfile: ./worker/Dockerfile
    env_file: ./worker/.env
    ports:
     - "${PORT:-8081}:8081"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    container_name: dryink-postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dryink
    volumes:
      - dryink_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
   
  redis:
    container_name: dryink_redis
    image: redis:alpine
    ports:
     - 6379:6379
    volumes:
      - dryink-redis-data:/data

volumes:
  dryink_db_data:
  dryink-redis-data:
